project:
  type: website
  output-dir: ../../_site/blog

website:
  page-navigation: true
  back-to-top-navigation: true
  search:
    type: overlay

format:
  html:
    quarto-required: 1.*
    toc: true
    number-sections: true
    number-depth: 2
    code-fold: show
    code-link: true

lang: en

execute:
  freeze: true
